app/models/Rate.php
<?php

namespace app\models;
use app\models\Currency;

class Rate extends \yii\db\ActiveRecord
{
    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public static function tableName()
    {
        return 'rate';
    }

    /**
     * @return array primary key of the table
     **/
    public static function primaryKey()
    {
        return array('id');
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id' => 'ID',
            'from_currency_id' => 'from_currency_id',
            'to_currency_id' => 'to_currency_id',
            'from_ammount' => 'Title',
            'to_ammount' => 'Billing ID'
        );
    }

    public function getFrom()
    {
        return $this->hasOne(Currency::className(), ['id' => 'from_currency_id'])
            ->from(Currency::tableName() . ' ta');
    }
    public function getTo()
    {
        return $this->hasOne(Currency::className(), ['id' => 'to_currency_id']);
    }

}

app/controllers/BillingController.php
<?php

namespace app\controllers;
use yii\helpers\Url;

use Yii;
use yii\web\Controller;
use app\models\Billing;

class BillingController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionDelete($id=NULL)
    {
        if ($id === NULL)
        {
            Yii::$app->session->setFlash('PostDeletedError');
            Yii::$app->getResponse()->redirect(array(Url::home()));
        }
        $billing = Billing::findOne($id);
        if ($billing === NULL)
        {
            Yii::$app->session->setFlash('PostDeletedError');
            return $this->goBack();
        }
        $billing->delete();
        Yii::$app->session->setFlash('PostDeleted');
        $this->goBack();

    }

    public function actionCreate()
    {
        $model = new Billing;
        if ($_POST)
        {
            $model->name = $_POST['name'];

            if ($model->save())
        	$this->goBack();
        }

        echo $this->render('create', array(
            'model' => $model
        ));
    }
}

app/controllers/CurrencyController.php
<?php

namespace app\controllers;
use yii\helpers\Url;

use Yii;
use yii\web\Controller;
use app\models\Currency;
use app\models\Billing;

class CurrencyController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionDelete($id=NULL)
    {
        if ($id === NULL)
        {
            Yii::$app->session->setFlash('PostDeletedError');
            $this->goBack();
        }
        $item = Currency::findOne($id);
        if ($item === NULL)
        {
            Yii::$app->session->setFlash('PostDeletedError');
            $this->goBack();
        }
        $item->delete();

        Yii::$app->session->setFlash('PostDeleted');
        $this->goBack();
    }

    public function actionGet($id){
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $m = new Currency();
        $i = $m->findOne($id);
        return $i;
    }

    public function actionBilling($id){
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $m = new Currency();
        $i = $m->find()->where(['billing_id' => $id])->all();
        return $i;
    }

    public function actionCreate()
    {
        $model = new Currency;
        if ($_POST)
        {
            $model->name = $_POST['name'];
            $model->billing_id = $_POST['billing_id'];

            if ($model->save())
                $this->goBack();
        }

        $billing = new Billing;

        echo $this->render('create', array(
            'model' => $model,
            'data' => [
                'billings' => $billing->find()->all()
            ]
        ));
    }
}

app/controllers/RateController.php
<?php

namespace app\controllers;
use yii\helpers\Url;

use Yii;
use yii\web\Controller;
use app\models\Currency;
use app\models\Billing;
use app\models\Rate;

class RateController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionDelete($id=NULL)
    {
        if ($id === NULL)
        {
            Yii::$app->session->setFlash('PostDeletedError');
            $this->goBack();
        }
        $item = Rate::findOne($id);
        if ($item === NULL)
        {
            Yii::$app->session->setFlash('PostDeletedError');
            $this->goBack();
        }
        $item->delete();

        Yii::$app->session->setFlash('PostDeleted');
        $this->goBack();
    }

    public function actionGet($from_currency_id, $to_currency_id){
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $i = Rate::find()->where(['from_currency_id' => $from_currency_id, 'to_currency_id' => $to_currency_id])->all();
        if (empty($i)) return array('status' => 'NeN');
        else return $i;
    }

    public function actionCreate()
    {
        $model = new Rate;
        if ($_POST)
        {
            $model->from_currency_id = $_POST['from_currency_id'];
            $model->to_currency_id = $_POST['to_currency_id'];
            $model->from_ammount = $_POST['from_ammount'];
            $model->to_ammount = $_POST['to_ammount'];

            if ($model->save())
                $this->goBack();
        }

        $billing = new Billing;
        $currency = new Currency();

        echo $this->render('create', array(
            'model' => $model,
            'data' => [
                'currencies' => $currency->find()->all(),
                'billings' => $billing->find()->all()
            ]
        ));
    }
}

app/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\Billing;
use app\models\Currency;
use app\models\Rate;

class SiteController extends Controller
{

    public function actionIndex(){
        $billing = new Billing;
        $currency = new Currency;
        $rate = new Rate;
        echo $this->render('index', array(
            'data' => [
                'billings' => $billing->find()->all(),
                'currency' => $currency->find()->joinWith('billings')->all(),
                'rate' => $rate->find()->joinWith('from')->joinWith('to')->all()
            ]
        ));
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

}

app/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

app/views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'My Yii Application';
?>

<script> var toWork = true; </script>

<div class="site-index">

    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <h1>Currency exchange - Test task</h1>
                <p>Lorem ipsum set dolor is..</p>
            </div>
            <hr>
            <div class="col-md-3">
                <div class="row">
                    <select name="billing1" id="billing1" class="form-control">
                        <option value="">
                            <?php foreach ($data['billings'] as $item): ?>
                                <option value="<?= Html::decode($item->id); ?>">
                                    <?= Html::decode($item->name); ?>
                                </option>
                            <?php endforeach; ?>
                    </select>
                </div>
                <hr>
                <div class="row">
                    <select name="billing2" id="billing2" class="form-control">
                        <option value="">
                            <?php foreach ($data['billings'] as $item): ?>
                        <option value="<?= Html::decode($item->id); ?>">
                            <?= Html::decode($item->name); ?>
                        </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <hr>
            </div>
            <div class="col-md-3 col-md-offset-1">
                <div id="currencies-panel" style="display: none;">
                    <div class="row">
                        <select name="from_currency_id" id="from_currency_id" class="form-control">
                        </select>
                    </div>
                    <hr>
                    <div class="row">
                        <select name="to_currency_id" id="to_currency_id" class="form-control">
                        </select>
                    </div>
                    <hr>
                </div>
            </div>
            <div class="col-md-3 col-md-offset-1">
                <div id="ammount-panel"></div>
            </div>
        </div>
    </div>
    <p>&nbsp;</p>
    <p>Some text here</p>
    <hr>
	<?php if(!Yii::$app->user->isGuest): ?>
    <div class="row">
        <h2>Admin tools</h2>
        <hr>
        <div class="col-md-4">
            <?= Html::a('Add billing', array('billing/create'), array('class' => 'btn btn-primary pull-right')); ?>
            <div class="clearfix"></div>
            <h3>Billings</h3>
            <table class="table table-striped table-hover">
                <tr>
                    <td>#</td>
                    <td>Name</td>
                    <td></td>
                </tr>
                <?php foreach ($data['billings'] as $item): ?>
                    <tr>
                        <td>
                            <?= Html::decode($item->id); ?>
                        </td>
                        <td><?= Html::decode($item->name); ?></td>
                        <td class="text-center">
                            <?= Html::a(NULL, array('billing/delete', 'id'=>$item->id), array('class'=>'fa fa-trash')); ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
        <div class="col-md-4">
            <?= Html::a('Add currency', array('currency/create'), array('class' => 'btn btn-primary pull-right')); ?>
            <div class="clearfix"></div>
            <h3>Curenncies</h3>
            <table class="table table-striped table-hover">
                <tr>
                    <td>#</td>
                    <td>Name</td>
                    <td>Billing</td>
                    <td></td>
                </tr>
                <?php foreach ($data['currency'] as $item): ?>
                    <tr>
                        <td>
                            <?= Html::decode($item->id); ?>
                        </td>
                        <td><?= Html::decode($item->name); ?></td>
                        <td>
                            <?= Html::decode($item->billings->name); ?>
                        </td>
                        <td class="text-center">
                            <?= Html::a(NULL, array('currency/delete', 'id'=>$item->id), array('class'=>'fa fa-trash')); ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
        <div class="col-md-4">
            <?= Html::a('Add rate', array('rate/create'), array('class' => 'btn btn-primary pull-right')); ?>
            <div class="clearfix"></div>
            <h3>Rates</h3>
            <table class="table table-striped table-hover">
                <tr>
                    <td>#</td>
                    <td>From</td>
                    <td>To</td>
                    <td>Rates</td>
                    <td>Options</td>
                </tr>
                <?php foreach ($data['rate'] as $item): ?>
                    <tr>
                        <td>
                            <?= $item->id; ?>
                        </td>
                        <td>
                            #<?= $item->from_currency_id?> <?= $item->from->name; ?>
                        </td>
                        <td>
                            #<?= $item->to_currency_id?> <?= $item->to->name; ?>
                        </td>
                        <td>
                            <?= $item->from_ammount ?> / <?= $item->to_ammount; ?>
                        </td>
                        <td class="text-center">
                            <?= Html::a(NULL, array('rate/delete', 'id'=>$item->id), array('class'=>'fa fa-trash')); ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <hr>
                <?php endif; ?>

</div>

app/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username') ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>